# Azure Pipelines - Manual E2E Test Execution
# Equivalent to .github/workflows/01-manual-exec.yaml

pr: none  # No PR trigger
trigger: none  # No CI trigger; manual only

pool:
  vmImage: ubuntu-latest

parameters:
  - name: nome
    displayName: 'Nome do pipeline'
    type: string
    default: 'Execucao Manual'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: npm install -g yarn
  displayName: 'Instalando Yarn'

- script: yarn
  displayName: 'Instalando dependencias'

- script: yarn playwright install
  displayName: 'Instalando Playwright'

- script: yarn playwright test
  displayName: 'Executando Testes e2e'
