#Ci de Nivel 1 - Disparo manual a partir do 1 clique 

# nome do nosso 'pipeline'
name: 'Execucao Manual'
# regras de disparo (gatilho/trigger)
on:
  workflow_dispatch:
    inputs:
      nome:
        description: 'Nome do pipeline'
        required: true
        default: 'Execucao Manual'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing node  
        uses: actions/setup-node@v4
        with:
            node-version: 22.x
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Installando dependencias
        run: yarn 
      - name: Instalando Playwright
        run: yarn playwright install
      - name: Executando Testes e2e
        run: yarn playwright test
     
        