# CI de nivel 04 - Disparo dos testes dentro do pipe de dev 

name : 'Execução de testes integrados'

on: 
   workflow_dispatch:

jobs:
    inspecao:
      runs-on: ubuntu-latest

      steps: 
        - uses: actions/checkout@v4

        - name: Instalando Yarn
          run: npm install -g yarn

        - name: Instalar dependencias
          run: yarn 

        - name: Checando padronizacao do Codigo
          run: yarn lint

    unidade:
      runs-on: ubuntu-latest

      steps: 
        - name: Instalando Yarn
          run: npm install -g yarn
        - name: Instalar dependencias
          run: yarn 

        - name: Executando testes de unidade
          run: yarn test

    e2e-tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Installing node  
          uses: actions/setup-node@v4
          with:
            node-version: 22.x
        - name: Instalando Yarn
          run: npm install -g yarn
        - name: Installando dependencias
          run: yarn 
        - name: Instalando Playwright
          run: yarn playwright install
        - name: Executando Testes e2e
          run: yarn playwright test
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report  
    deploy: 
      runs-on: ubuntu-latest 

      steps: 
        - name: Simulando deploy
          run: echo "Deploy realizado com sucesso"

    # condicional - if 
    # `${ expressao }`
    # == comparacao  
     
    
